---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: mvbcoding/awslinux
  - name: centos-7.1

suites:
  - name: jboss
    run_list: 
      - recipe[jboss::default]
    attributes:
      jboss:
        ear_files:
          - source_path: 'https://developer.jboss.org/servlet/JiveServlet/download/588885-27216'
            ear_file: HelloWorld.ear
