---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: mvbcoding/awslinux
  - name: centos-7.1

suites:
  - name: jboss
    run_list: 
      - recipe[jboss::default]
    attributes:
      jboss:
        ear_files:
          - '/tmp/HelloWorldApp.ear'

