name             'jboss'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures jboss'
long_description 'Installs/Configures jboss'
version          '0.1.0'
